// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace lzengine
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StartzoneTable : ITableObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public ITableObject InitTable(ByteBuffer _bb) { return StartzoneTable.GetRoot( _bb, this); }
  public static StartzoneTable GetRoot(ByteBuffer _bb) { return GetRoot(_bb, new StartzoneTable()); }
  public static StartzoneTable GetRoot(ByteBuffer _bb, StartzoneTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool Verify(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, StartzoneTableVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StartzoneTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public lzengine.StartzoneItem? Datas(int j) { int o = __p.__offset(4); return o != 0 ? (lzengine.StartzoneItem?)(new lzengine.StartzoneItem()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DatasLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public lzengine.StartzoneItem? DatasByKey(int key) { int o = __p.__offset(4); return o != 0 ? lzengine.StartzoneItem.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<lzengine.StartzoneTable> Create(FlatBufferBuilder builder,
      VectorOffset datasOffset = default(VectorOffset)) {
    builder.StartTable(1);
    StartzoneTable.AddDatas(builder, datasOffset);
    return StartzoneTable.End(builder);
  }

  public static void Start(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDatas(FlatBufferBuilder builder, VectorOffset datasOffset) { builder.AddOffset(0, datasOffset.Value, 0); }
  public static VectorOffset CreateDatasVector(FlatBufferBuilder builder, Offset<lzengine.StartzoneItem>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDatasVectorBlock(FlatBufferBuilder builder, Offset<lzengine.StartzoneItem>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDatasVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<lzengine.StartzoneItem>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDatasVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<lzengine.StartzoneItem>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDatasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<lzengine.StartzoneTable> End(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<lzengine.StartzoneTable>(o);
  }
  public static void Finish(FlatBufferBuilder builder, Offset<lzengine.StartzoneTable> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixed(FlatBufferBuilder builder, Offset<lzengine.StartzoneTable> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class StartzoneTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Datas*/, lzengine.StartzoneItemVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct StartzoneItem : ITableObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public ITableObject InitTable(ByteBuffer _bb) { return StartzoneItem.GetRoot( _bb, this); }
  public static StartzoneItem GetRoot(ByteBuffer _bb) { return GetRoot(_bb, new StartzoneItem()); }
  public static StartzoneItem GetRoot(ByteBuffer _bb, StartzoneItem obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StartzoneItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int _Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string _Dbconnection { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> Get_DbconnectionBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? Get_DbconnectionBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] Get_DbconnectionArray() { return __p.__vector_as_array<byte>(6); }
  public string _Dbname { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> Get_DbnameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? Get_DbnameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] Get_DbnameArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<lzengine.StartzoneItem> Create(FlatBufferBuilder builder,
      int _id = 0,
      StringOffset _dbconnectionOffset = default(StringOffset),
      StringOffset _dbnameOffset = default(StringOffset)) {
    builder.StartTable(3);
    StartzoneItem.Add_Dbname(builder, _dbnameOffset);
    StartzoneItem.Add_Dbconnection(builder, _dbconnectionOffset);
    StartzoneItem.Add_Id(builder, _id);
    return StartzoneItem.End(builder);
  }

  public static void Start(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void Add_Id(FlatBufferBuilder builder, int _Id) { builder.AddInt(0, _Id, 0); }
  public static void Add_Dbconnection(FlatBufferBuilder builder, StringOffset _DbconnectionOffset) { builder.AddOffset(1, _DbconnectionOffset.Value, 0); }
  public static void Add_Dbname(FlatBufferBuilder builder, StringOffset _DbnameOffset) { builder.AddOffset(2, _DbnameOffset.Value, 0); }
  public static Offset<lzengine.StartzoneItem> End(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<lzengine.StartzoneItem>(o);
  }

  public static VectorOffset CreateSortedVectorOfStartzoneItem(FlatBufferBuilder builder, Offset<StartzoneItem>[] offsets) {
    Array.Sort(offsets,
      (Offset<StartzoneItem> o1, Offset<StartzoneItem> o2) =>
        new StartzoneItem().__assign(builder.DataBuffer.Length - o1.Value, builder.DataBuffer)._Id.CompareTo(new StartzoneItem().__assign(builder.DataBuffer.Length - o2.Value, builder.DataBuffer)._Id));
    return builder.CreateVectorOfTables(offsets);
  }

  public static StartzoneItem? __lookup_by_key(int vectorLocation, int key, ByteBuffer bb) {
    StartzoneItem obj_ = new StartzoneItem();
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      obj_.__assign(tableOffset, bb);
      int comp = obj_._Id.CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return obj_;
      }
    }
    return null;
  }
}


static public class StartzoneItemVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*_Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*_Dbconnection*/, false)
      && verifier.VerifyString(tablePos, 8 /*_Dbname*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
