// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace lzengine
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct StartmachineTable : ITableObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public ITableObject InitTable(ByteBuffer _bb) { return StartmachineTable.GetRoot( _bb, this); }
  public static StartmachineTable GetRoot(ByteBuffer _bb) { return GetRoot(_bb, new StartmachineTable()); }
  public static StartmachineTable GetRoot(ByteBuffer _bb, StartmachineTable obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool Verify(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, StartmachineTableVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StartmachineTable __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public lzengine.StartmachineItem? Datas(int j) { int o = __p.__offset(4); return o != 0 ? (lzengine.StartmachineItem?)(new lzengine.StartmachineItem()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DatasLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public lzengine.StartmachineItem? DatasByKey(int key) { int o = __p.__offset(4); return o != 0 ? lzengine.StartmachineItem.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<lzengine.StartmachineTable> Create(FlatBufferBuilder builder,
      VectorOffset datasOffset = default(VectorOffset)) {
    builder.StartTable(1);
    StartmachineTable.AddDatas(builder, datasOffset);
    return StartmachineTable.End(builder);
  }

  public static void Start(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddDatas(FlatBufferBuilder builder, VectorOffset datasOffset) { builder.AddOffset(0, datasOffset.Value, 0); }
  public static VectorOffset CreateDatasVector(FlatBufferBuilder builder, Offset<lzengine.StartmachineItem>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDatasVectorBlock(FlatBufferBuilder builder, Offset<lzengine.StartmachineItem>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDatasVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<lzengine.StartmachineItem>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDatasVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<lzengine.StartmachineItem>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDatasVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<lzengine.StartmachineTable> End(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<lzengine.StartmachineTable>(o);
  }
  public static void Finish(FlatBufferBuilder builder, Offset<lzengine.StartmachineTable> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixed(FlatBufferBuilder builder, Offset<lzengine.StartmachineTable> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class StartmachineTableVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Datas*/, lzengine.StartmachineItemVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct StartmachineItem : ITableObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public ITableObject InitTable(ByteBuffer _bb) { return StartmachineItem.GetRoot( _bb, this); }
  public static StartmachineItem GetRoot(ByteBuffer _bb) { return GetRoot(_bb, new StartmachineItem()); }
  public static StartmachineItem GetRoot(ByteBuffer _bb, StartmachineItem obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public StartmachineItem __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int _Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string _Innerip { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> Get_InneripBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? Get_InneripBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] Get_InneripArray() { return __p.__vector_as_array<byte>(6); }
  public string _Outerip { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> Get_OuteripBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? Get_OuteripBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] Get_OuteripArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<lzengine.StartmachineItem> Create(FlatBufferBuilder builder,
      int _id = 0,
      StringOffset _inneripOffset = default(StringOffset),
      StringOffset _outeripOffset = default(StringOffset)) {
    builder.StartTable(3);
    StartmachineItem.Add_Outerip(builder, _outeripOffset);
    StartmachineItem.Add_Innerip(builder, _inneripOffset);
    StartmachineItem.Add_Id(builder, _id);
    return StartmachineItem.End(builder);
  }

  public static void Start(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void Add_Id(FlatBufferBuilder builder, int _Id) { builder.AddInt(0, _Id, 0); }
  public static void Add_Innerip(FlatBufferBuilder builder, StringOffset _InneripOffset) { builder.AddOffset(1, _InneripOffset.Value, 0); }
  public static void Add_Outerip(FlatBufferBuilder builder, StringOffset _OuteripOffset) { builder.AddOffset(2, _OuteripOffset.Value, 0); }
  public static Offset<lzengine.StartmachineItem> End(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<lzengine.StartmachineItem>(o);
  }

  public static VectorOffset CreateSortedVectorOfStartmachineItem(FlatBufferBuilder builder, Offset<StartmachineItem>[] offsets) {
    Array.Sort(offsets,
      (Offset<StartmachineItem> o1, Offset<StartmachineItem> o2) =>
        new StartmachineItem().__assign(builder.DataBuffer.Length - o1.Value, builder.DataBuffer)._Id.CompareTo(new StartmachineItem().__assign(builder.DataBuffer.Length - o2.Value, builder.DataBuffer)._Id));
    return builder.CreateVectorOfTables(offsets);
  }

  public static StartmachineItem? __lookup_by_key(int vectorLocation, int key, ByteBuffer bb) {
    StartmachineItem obj_ = new StartmachineItem();
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      obj_.__assign(tableOffset, bb);
      int comp = obj_._Id.CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return obj_;
      }
    }
    return null;
  }
}


static public class StartmachineItemVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*_Id*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*_Innerip*/, false)
      && verifier.VerifyString(tablePos, 8 /*_Outerip*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
